### ISSUE TITLE
MySQL　DDL问题

### ISSUE THREAD

**Issue by gg2038** [86dbs/dbsyncer#5]
DBsyncer同步不了 DDL吗，即使是源端和目标端手工加字段后，再重启同步链路，都不无法同步新增字段的数据，这点我是想不通啊，为什么 呢？

**Comment by lifejwang11** [comment]
目前支持db的标准写法，支持语句请[查看](https://gitee.com/ghi/dbsyncer/wikis/%E5%BF%AB%E9%80%9F%E4%BA%86%E8%A7%A3/%E8%A1%A8%E7%BB%93%E6%9E%84%E5%90%8C%E6%AD%A5)
