### ISSUE TITLE
SQLSERVER 2012增量同步自动停止。CDC表数据仍然在继续执行

### ISSUE THREAD

**Issue by alangcool** [86dbs/dbsyncer#6]
建了有10多个驱动，其中有几个驱动表数据大概10万，每天更新2万左右。今天一看10.8号就停止同步了。重启startup.bat也没用。这是啥原因。

**Comment by alangcool** [comment]
版本是1.2.4-RC

**Comment by 86dbs** [comment]
连接过期问题，请升级到1.2.7 版本已修复：https://gitee.com/ghi/dbsyncer/releases
