### ISSUE TITLE
没有主键的表应该如何同步

### ISSUE THREAD

**Issue by 692568516** [86dbs/dbsyncer#7]
大佬好。在实际使用中，会有部分表没有主键，这时候则无法添加任务，类似这种如何支持，是否有像Debezium 类似提供一个none的选项，不考虑数据重复，先让同步

**Comment by 86dbs** [comment]
![image](https://github.com/86dbs/dbsyncer/assets/25784292/595e8a17-fc41-4e5f-863b-575e3dfb9220)

支持自定义定义主键

**Comment by 692568516** [comment]
表每列数据都有重复的数据，自定义主键的话就会提示主键冲突

**Comment by 86dbs** [comment]
> 表每列数据都有重复的数据，自定义主键的话就会提示主键冲突

不符合规范，建议自定义主键，保证行数据唯一性。

**Comment by 692568516** [comment]
好的谢谢
